// Generates RuleR overload signatures for tison.ts
// Run: npx ts-node scripts/gen-ruler-overloads.ts [--output src/ruler-overloads.ts] [--max 12]

import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

const args = process.argv.slice(2);
const max = parseInt(args.find(a => a.startsWith('--max='))?.split('=')[1] ?? '12', 10) || 12;
const outPath = args.find(a => a.startsWith('--output='))?.split('=')[1] ?? './scripts/output/ruler-overloads.ts';

function gen(max: number): string {
	const lines: string[] = [];

	// Type aliases (shared with existing code)
	lines.push('// --- Generated by scripts/gen-ruler-overloads.ts ---');
	lines.push('// Do not edit manually. Run `npx ts-node scripts/gen-ruler-overloads.ts` to regenerate.');
	lines.push('');
	
	// Helper types — only emit if they don't exist in user's code already
	lines.push('type SymR<A extends readonly unknown[], C = any> = string | RegExp | Terminal | Rules<any> | (() => Rules<any>) | Ref<any> | Action<any, C, ValuesOfR<A>>;');
	lines.push('type RSymR<T, A extends readonly unknown[], C = any> = Terminal<T> | Rules<T> | (() => Rules<T>) | Ref<T> | Action<T, C, ValuesOfR<A>>;');
	lines.push('type ValuesOfR<T extends readonly unknown[]> = { [K in keyof T]: ElemValue<T[K]> };');
	lines.push('');

	for (let n = 1; n <= max; n++) {
		const typeParams: string[] = ['T', 'C'];
		const paramDecls: string[] = [];
		let constraintChain = ''; // for constructing S2..Sn constraints

		for (let i = 0; i < n; i++) {
			typeParams.push(`S${i + 1}`);
			if (i === 0) {
				paramDecls.push(`s${i + 1}: RSymR<T, [], C>`);
			} else {
				const prevTypes = Array.from({ length: i }, (_, j) => `S${j + 1}`).join(', ');
				paramDecls.push(`s${i + 1} extends SymR<[${prevTypes}], C>, s${i + 1}: RSymR<T, [${prevTypes}], C>`);
			}
		}

		const params = paramDecls.join(', ');
		lines.push(`export function RuleR<${typeParams.join(', ')}>(${params}): Rule<T>;`);
	}

	// Implementation signature + body
	lines.push('');
	lines.push("export function RuleR(...syms: any[]): any {");
	lines.push("  const last = syms.at(-1);");
	lines.push("  if (typeof last === 'function' && last.length > 0)");
	lines.push("    return Rule(syms.slice(0, -1), last);");
	lines.push("  return Rule(syms, (values: any[]) => values[values.length - 1]);");
	lines.push('}');

	return lines.join('\n') + '\n';
}

const output = gen(max);

// Create directory if needed
const outDir = dirname(resolve(outPath));
try { mkdirSync(outDir, { recursive: true }); } catch {}
writeFileSync(outPath, output);
console.log(`Generated ${max} RuleR overloads → ${outPath}`);
