// Generates RuleR overload signatures for tison.ts
// Run: npx ts-node scripts/gen-ruler-overloads.ts [--output src/ruler-overloads.ts] [--max 12]

import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve, relative } from 'node:path';

const args = process.argv.slice(2);
const max = parseInt(args.find(a => a.startsWith('--max='))?.split('=')[1] ?? '12', 10) || 12;
const outPath = args.find(a => a.startsWith('--output='))?.split('=')[1] ?? __dirname + '/output/ruler-overloads.ts';

function gen(max: number): string {
	const lines: string[] = [];

	lines.push(`// --- Generated by scripts/gen-ruler-overloads.ts ---
// Do not edit manually. Run 'npx ts-node scripts/gen-ruler-overloads.ts' to regenerate.

import { Rule, Action, Ref, Terminal, Rules, ElemValue, CommonAction, maybeCommonAction } from '${relative(dirname(outPath), __dirname + '/../src') || '.'}/tison';

// Rest-parameter alternative to Rule(): pass rhs symbols directly instead of wrapping them in an array literal with 'as const'.
// Any parameter may be an inline action -- it's typed against exactly the parameters that precede it.
// The rule's own result defaults to whatever the *last* argument evaluates to.

type ValuesOfR<T extends readonly unknown[]>	= { [K in keyof T]: ElemValue<T[K]> };

// Pins ctx's type to 'C' for every rule built with the returned function
export function makeRuleR<C>(commonAction?: CommonAction<C>) {
	type SymR<A extends readonly unknown[]>		= string | RegExp | Terminal | Rules<any> | (()=>Rules<any>) | Ref<any> | Action<any, C, ValuesOfR<A>>;
	type RSymR<T, A extends readonly unknown[]>	= Terminal<T> | Rules<T> | (()=>Rules<T>) | Ref<T> | Action<T, C, ValuesOfR<A>>;
	const common = maybeCommonAction(commonAction);
`);

	for (let n = 1; n <= max; n++) {
		const typeParams: string[] = ['T'];

		for (let i = 0; i < n - 1; i++)
			typeParams.push(`S${i + 1} extends SymR<[${Array.from({ length: i }, (_, j) => `S${j + 1}`).join(', ')}]>`);

		// The trailing symbol's type is written directly as RSymR<T, [...]> (not its own constrained
		// type parameter) so T sits in an inferable parameter position -- TS can't infer T through
		// another type parameter's `extends` clause, which is why that used to fall back to `unknown`.
		lines.push(`\tfunction rule<${typeParams.join(', ')}>(${[
			...Array.from({length: n - 1}, (_, j) => `s${j + 1}: S${j + 1}`),
			`s${n}: RSymR<T, [${Array.from({ length: n - 1 }, (_, j) => `S${j + 1}`).join(', ')}]>`,
		].join(', ')}): Rule<T>;`);
	}

	// Implementation signature + body
	lines.push(`
	function rule(...syms: any) {
		const last = syms.at(-1);
		if (typeof last === 'function' && last.length > 0)
			return Rule(syms.slice(0, -1), common(last));
		return Rule(syms, common((values: any[]) => values[values.length - 1]));
	}
	return rule;`
	);

	lines.push('}');
	lines.push(`export const RuleR = makeRuleR<any>();`);

	return lines.join('\n') + '\n';
}

const output = gen(max);

// Create directory if needed
const outDir = dirname(resolve(outPath));
try { mkdirSync(outDir, { recursive: true }); } catch {/*nothing*/}
writeFileSync(outPath, output);
console.log(`Generated ${max} RuleR overloads → ${outPath}`);
