// --- Generated by scripts/gen-ruler-overloads.ts ---
// Do not edit manually. Run 'npx ts-node scripts/gen-ruler-overloads.ts' to regenerate.

import { Rule, Action, Ref, Terminal, Rules, ElemValue, CommonAction, maybeCommonAction } from './tison';

// Rest-parameter alternative to Rule(): pass rhs symbols directly instead of wrapping them in an array literal with 'as const'.
// Any parameter may be an inline action -- it's typed against exactly the parameters that precede it.
// The rule's own result defaults to whatever the *last* argument evaluates to.

type ValuesOfR<T extends readonly unknown[]>	= { [K in keyof T]: ElemValue<T[K]> };

// Pins ctx's type to 'C' for every rule built with the returned function
export function makeRuleR<C>(commonAction?: CommonAction<C>) {
	type SymR<A extends readonly unknown[]>		= string | RegExp | Terminal | Rules<any> | (()=>Rules<any>) | Ref<any> | Action<any, C, ValuesOfR<A>>;
	type RSymR<T, A extends readonly unknown[]>	= Terminal<T> | Rules<T> | (()=>Rules<T>) | Ref<T> | Action<T, C, ValuesOfR<A>>;
	const common = maybeCommonAction(commonAction);

	function rule<T>(s1: RSymR<T, []>): Rule<T>;
	function rule<T, S1 extends SymR<[]>>(s1: S1, s2: RSymR<T, [S1]>): Rule<T>;
	function rule<T, S1 extends SymR<[]>, S2 extends SymR<[S1]>>(s1: S1, s2: S2, s3: RSymR<T, [S1, S2]>): Rule<T>;
	function rule<T, S1 extends SymR<[]>, S2 extends SymR<[S1]>, S3 extends SymR<[S1, S2]>>(s1: S1, s2: S2, s3: S3, s4: RSymR<T, [S1, S2, S3]>): Rule<T>;
	function rule<T, S1 extends SymR<[]>, S2 extends SymR<[S1]>, S3 extends SymR<[S1, S2]>, S4 extends SymR<[S1, S2, S3]>>(s1: S1, s2: S2, s3: S3, s4: S4, s5: RSymR<T, [S1, S2, S3, S4]>): Rule<T>;
	function rule<T, S1 extends SymR<[]>, S2 extends SymR<[S1]>, S3 extends SymR<[S1, S2]>, S4 extends SymR<[S1, S2, S3]>, S5 extends SymR<[S1, S2, S3, S4]>>(s1: S1, s2: S2, s3: S3, s4: S4, s5: S5, s6: RSymR<T, [S1, S2, S3, S4, S5]>): Rule<T>;
	function rule<T, S1 extends SymR<[]>, S2 extends SymR<[S1]>, S3 extends SymR<[S1, S2]>, S4 extends SymR<[S1, S2, S3]>, S5 extends SymR<[S1, S2, S3, S4]>, S6 extends SymR<[S1, S2, S3, S4, S5]>>(s1: S1, s2: S2, s3: S3, s4: S4, s5: S5, s6: S6, s7: RSymR<T, [S1, S2, S3, S4, S5, S6]>): Rule<T>;
	function rule<T, S1 extends SymR<[]>, S2 extends SymR<[S1]>, S3 extends SymR<[S1, S2]>, S4 extends SymR<[S1, S2, S3]>, S5 extends SymR<[S1, S2, S3, S4]>, S6 extends SymR<[S1, S2, S3, S4, S5]>, S7 extends SymR<[S1, S2, S3, S4, S5, S6]>>(s1: S1, s2: S2, s3: S3, s4: S4, s5: S5, s6: S6, s7: S7, s8: RSymR<T, [S1, S2, S3, S4, S5, S6, S7]>): Rule<T>;
	function rule<T, S1 extends SymR<[]>, S2 extends SymR<[S1]>, S3 extends SymR<[S1, S2]>, S4 extends SymR<[S1, S2, S3]>, S5 extends SymR<[S1, S2, S3, S4]>, S6 extends SymR<[S1, S2, S3, S4, S5]>, S7 extends SymR<[S1, S2, S3, S4, S5, S6]>, S8 extends SymR<[S1, S2, S3, S4, S5, S6, S7]>>(s1: S1, s2: S2, s3: S3, s4: S4, s5: S5, s6: S6, s7: S7, s8: S8, s9: RSymR<T, [S1, S2, S3, S4, S5, S6, S7, S8]>): Rule<T>;
	function rule<T, S1 extends SymR<[]>, S2 extends SymR<[S1]>, S3 extends SymR<[S1, S2]>, S4 extends SymR<[S1, S2, S3]>, S5 extends SymR<[S1, S2, S3, S4]>, S6 extends SymR<[S1, S2, S3, S4, S5]>, S7 extends SymR<[S1, S2, S3, S4, S5, S6]>, S8 extends SymR<[S1, S2, S3, S4, S5, S6, S7]>, S9 extends SymR<[S1, S2, S3, S4, S5, S6, S7, S8]>>(s1: S1, s2: S2, s3: S3, s4: S4, s5: S5, s6: S6, s7: S7, s8: S8, s9: S9, s10: RSymR<T, [S1, S2, S3, S4, S5, S6, S7, S8, S9]>): Rule<T>;
	function rule<T, S1 extends SymR<[]>, S2 extends SymR<[S1]>, S3 extends SymR<[S1, S2]>, S4 extends SymR<[S1, S2, S3]>, S5 extends SymR<[S1, S2, S3, S4]>, S6 extends SymR<[S1, S2, S3, S4, S5]>, S7 extends SymR<[S1, S2, S3, S4, S5, S6]>, S8 extends SymR<[S1, S2, S3, S4, S5, S6, S7]>, S9 extends SymR<[S1, S2, S3, S4, S5, S6, S7, S8]>, S10 extends SymR<[S1, S2, S3, S4, S5, S6, S7, S8, S9]>>(s1: S1, s2: S2, s3: S3, s4: S4, s5: S5, s6: S6, s7: S7, s8: S8, s9: S9, s10: S10, s11: RSymR<T, [S1, S2, S3, S4, S5, S6, S7, S8, S9, S10]>): Rule<T>;
	function rule<T, S1 extends SymR<[]>, S2 extends SymR<[S1]>, S3 extends SymR<[S1, S2]>, S4 extends SymR<[S1, S2, S3]>, S5 extends SymR<[S1, S2, S3, S4]>, S6 extends SymR<[S1, S2, S3, S4, S5]>, S7 extends SymR<[S1, S2, S3, S4, S5, S6]>, S8 extends SymR<[S1, S2, S3, S4, S5, S6, S7]>, S9 extends SymR<[S1, S2, S3, S4, S5, S6, S7, S8]>, S10 extends SymR<[S1, S2, S3, S4, S5, S6, S7, S8, S9]>, S11 extends SymR<[S1, S2, S3, S4, S5, S6, S7, S8, S9, S10]>>(s1: S1, s2: S2, s3: S3, s4: S4, s5: S5, s6: S6, s7: S7, s8: S8, s9: S9, s10: S10, s11: S11, s12: RSymR<T, [S1, S2, S3, S4, S5, S6, S7, S8, S9, S10, S11]>): Rule<T>;

	function rule(...syms: any) {
		const last = syms.at(-1);
		if (typeof last === 'function' && last.length > 0)
			return Rule(syms.slice(0, -1), common(last));
		return Rule(syms, common((values: any[]) => values[values.length - 1]));
	}
	return rule;
}
export const RuleR = makeRuleR<any>();
